### PR TITLE
Roll Heroku breaking changes in #426 back to #416

### PR DESCRIPTION
**Pull request by reconstructions**
Starting in commit #421, pushing to Heroku failed with an asset compilation error as described in issue #429.  

This PR fixes pushing to Heroku by rolling back Yarn to version 0.22.0 and precisely specifying a LTS node version (8.9.3).  Using node 7.8.0 gave warnings about bugs and unstable performance and was not a long-term support version.  Inadvertently using node versions other than 8.9.3 also produced other errors when pushing to Heroku (ranges were specified in the package.json engines section).

All other gems and node packages were advanced to the latest versions, with the exceptions of those which were locked back to avoid breaking changes.

All tests are green, all linting is green, ActionCable is working, and there are only one or two deprecation warnings which still need fixing.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/431)

### CODE REVIEW

**Comment by justin808** [comment]
Current version of yarn is greater than 1.3.2. Let's try to update to the current yarn.

**Comment by reconstructions** [comment]
I tried a number of different Yarn versions later than 0.22.0, and all failed pushing to Heroku.  I tried to bump Yarn forward to 0.23.x?, and that failed the same way.  Isn't 1.3.2 the [latest version](https://github.com/yarnpkg/yarn/releases)?  

I am still working on trying to figure this one out.  I want to make sure there is nothing obvious in the react_on_rails rake task which might be causing this.  After checking that I will post issues on the other gems that could be contributing.  

Perhaps this could be a branch referenced in #429 rather than a PR, so that if anyone else is stuck they can see how to quickly patch it?  Let me know what you think...

**Comment by LizPrescott** [comment]
Hi! Is this waiting for a code review, or do you need another pair of hands in the code? This bug is definitely affecting me, and I'd be happy to help fix it if I can.

**Comment by reconstructions** [comment]
Thanks Liz, I thought I saw a notice that another contributor's version of this had been merged sometime in the spring, but I couldn't track that down.  I tried to fix it for about a week, but I could never get newer versions of Yarn to deploy on Heroku with React on Rails.  I put what I learned in #429 and locked Yarn back.  I have been working on another project so I am not sure where this stands now, sorry...

**Comment by justin808** [comment]
@reconstructions @LizPrescott I'd love a PR to bring the libraries of this up to current.

**Comment by justin808** [comment]
@LizPrescott @reconstructions Please feel free to re-open this one.
